version: '3'

services:
  app:
    build: .
    container_name: exfiltration-app
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./pcap:/app/pcap
      - shared-data:/app/data
    command: python fast_app.py --host 0.0.0.0 --port 8080
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped

volumes:
  shared-data: 